"""First migration

Revision ID: bd8c9bb7bbe8
Revises:
Create Date: 2020-05-24 20:13:58.353316

"""
import sqlalchemy as sa

from alembic import op
from utils.populate import pre_populate_artists

# revision identifiers, used by Alembic.
revision = "bd8c9bb7bbe8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    artist_table = op.create_table(
        "artist",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("popularity", sa.Integer(), nullable=False),
        sa.Column("updated_by_be", sa.Boolean(), default=False, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # pre-populate with a few artists
    op.bulk_insert(artist_table, pre_populate_artists())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artist")
    # ### end Alembic commands ###
